# Generated by Django 3.2.5 on 2021-07-27 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0004_realtor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('bedroom', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('inrastructure', models.FloatField(default=0.0)),
                ('detail', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('list_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('memorandum', models.FileField(upload_to='')),
                ('floor', models.IntegerField()),
                ('is_let', models.BooleanField()),
                ('is_sale', models.BooleanField()),
                ('hire_price', models.FloatField(default=0.0)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
