# Generated by Django 3.2.5 on 2021-07-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210727_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='hire_price',
            new_name='hire_price_Rial',
        ),
    ]
