# Generated by Django 3.2.5 on 2021-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_hire_price_listings_hire_price_rial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='is_let',
            field=models.BooleanField(default=False, verbose_name='let'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='sale'),
        ),
    ]
