# Generated by Django 3.2.5 on 2021-07-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210729_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='home_types',
            field=models.CharField(blank=True, default='مسکونی', max_length=70),
        ),
    ]
