# Generated by Django 3.2.5 on 2021-08-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listings_home_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
