# Generated by Django 3.2.5 on 2021-08-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listings_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='hire_price_Rial',
            new_name='price',
        ),
    ]
