# Generated by Django 3.2.5 on 2021-08-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_hire_price_rial_listings_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='home_types',
        ),
    ]
