# Generated by Django 3.2.5 on 2021-08-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listings_home_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
