# Generated by Django 3.2.5 on 2021-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listings_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='homeType',
            field=models.CharField(choices=[('V', 'Village'), ('آپارتمان', 'آپارتمان')], default='V', max_length=128),
        ),
    ]
