# Generated by Django 3.2.5 on 2021-08-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listings_hometype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='homeType',
        ),
        migrations.AddField(
            model_name='listings',
            name='types',
            field=models.CharField(choices=[('V', 'ویلا'), ('A', 'آپارتمان'), ('T', 'تجاری'), ('S', 'فروشگاه')], default='آپارتمان', max_length=128),
        ),
        migrations.AlterField(
            model_name='listings',
            name='city',
            field=models.CharField(choices=[('Gorgan', 'گرگان'), ('Kordkuy', 'کردکوی'), ('Bandargaz', 'بندرگز'), ('Gonbad', 'گنبد')], default='آپارتمان', max_length=128),
        ),
    ]
