# Generated by Django 3.2.5 on 2021-08-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20210809_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='condition',
            field=models.CharField(choices=[('اجاره', 'اجاره'), ('فروش', 'فروش')], default='اجاره', max_length=128),
        ),
    ]
