# Generated by Django 3.2.5 on 2021-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listings_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='types',
            field=models.CharField(choices=[('ویلا', 'ویلا'), ('آپارتمان', 'آپارتمان'), ('تجاری', 'تجاری'), ('فروشگاه', 'فروشگاه')], default='آپارتمان', max_length=128),
        ),
    ]
