# Generated by Django 3.2.5 on 2021-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listings_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='city',
            field=models.CharField(choices=[('گرگان', 'گرگان'), ('کردکوی', 'کردکوی'), ('بندرگز', 'بندرگز'), ('گنبد', 'گنبد')], default='آپارتمان', max_length=128),
        ),
    ]
