# Generated by Django 3.2.5 on 2021-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_singleblog_main_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleblog',
            old_name='description',
            new_name='body',
        ),
        migrations.AddField(
            model_name='singleblog',
            name='introduction',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
