# Generated by Django 3.2.5 on 2021-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
