# Generated by Django 3.2.5 on 2021-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_realtor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
