# Generated by Django 3.2.5 on 2021-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20210728_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='office',
            field=models.IntegerField(default='شماره + کد شهر'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.IntegerField(default='+98'),
        ),
    ]
