# Generated by Django 3.2.5 on 2021-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_auto_20210805_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='office',
            field=models.IntegerField(default=''),
        ),
    ]
