# Generated by Django 3.2.5 on 2021-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_alter_realtor_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='office',
            field=models.IntegerField(default='017'),
        ),
    ]
