# Generated by Django 3.2.5 on 2021-08-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0009_auto_20210805_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='office',
        ),
    ]
